-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.softcart_dimcategory
(
    category_id integer NOT NULL,
    category character varying COLLATE pg_catalog."default",
    CONSTRAINT softcart_dimcategory_pkey PRIMARY KEY (category_id)
);

CREATE TABLE IF NOT EXISTS public.softcart_dimcountry
(
    country_id integer NOT NULL,
    country character varying COLLATE pg_catalog."default",
    CONSTRAINT softcart_dimcountry_pkey PRIMARY KEY (country_id)
);

CREATE TABLE IF NOT EXISTS public.softcart_dimdate
(
    date_id serial NOT NULL,
    date date,
    day integer,
    weekday integer,
    weekday_name character varying(20) COLLATE pg_catalog."default",
    month integer,
    month_name character varying(20) COLLATE pg_catalog."default",
    year integer,
    quarter integer,
    quarter_name character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT softcart_dimdate_pkey PRIMARY KEY (date_id)
);

CREATE TABLE IF NOT EXISTS public.softcart_dimitem
(
    item_id integer NOT NULL,
    item character varying COLLATE pg_catalog."default",
    CONSTRAINT softcart_dimitem_pkey PRIMARY KEY (item_id)
);

CREATE TABLE IF NOT EXISTS public.softcart_factsales
(
    order_id integer NOT NULL,
    item_id integer,
    category_id integer,
    price numeric,
    country_id integer,
    date_id integer,
    CONSTRAINT softcart_factsales_pkey PRIMARY KEY (order_id)
);

ALTER TABLE IF EXISTS public.softcart_factsales
    ADD CONSTRAINT softcart_factsales_category_id_fkey FOREIGN KEY (category_id)
    REFERENCES public.softcart_dimcategory (category_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.softcart_factsales
    ADD CONSTRAINT softcart_factsales_country_id_fkey FOREIGN KEY (country_id)
    REFERENCES public.softcart_dimcountry (country_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.softcart_factsales
    ADD CONSTRAINT softcart_factsales_date_id_fkey FOREIGN KEY (date_id)
    REFERENCES public.softcart_dimdate (date_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.softcart_factsales
    ADD CONSTRAINT softcart_factsales_item_id_fkey FOREIGN KEY (item_id)
    REFERENCES public.softcart_dimitem (item_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;
